# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
#
# Configure Using Gemfile
# gem "pg"

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: clinic_management_system_development
  username: postgres    # Your PostgreSQL username
  password: password     # Your PostgreSQL password
  host: localhost        # Ensure you connect on a TCP socket
  port: 5432             # PostgreSQL default port

test:
  <<: *default
  database: clinic_management_system_test
  username: postgres     # Your PostgreSQL username
  password: password      # Your PostgreSQL password
  host: localhost         # Ensure you connect on a TCP socket
  port: 5432              # PostgreSQL default port

production:
  <<: *default
  database: clinic_management_system_production
  username: postgres      # Your PostgreSQL username
  password: password       # Your PostgreSQL password
  host: localhost          # Ensure you connect on a TCP socket
  port: 5432               # PostgreSQL default port
